[package]
name = "rust_test"
version = "0.1.0"
authors = ["Eoin O'Neill <eoinoneill1991@gmail.com>"]

[dependencies]
rand = "0.5.3"

[build-dependencies]
cbindgen = "0.6.0"

[lib]
name = "rust_test"
crate-type = ["staticlib"]
